apiVersion: v1
kind: Namespace
metadata:
  name: service-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service
  name: service
  namespace: service-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      - image: service-amd64:1.0
        name: service-amd64
